[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = "release"

